"""Update unique constraint of claim table

Revision ID: 92c0120a4566
Revises: 08e20d0fcb90
Create Date: 2023-11-12 02:23:17.615967

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "92c0120a4566"
down_revision: Union[str, None] = "08e20d0fcb90"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("claim_nonce_key", "claim", type_="unique")
    op.create_unique_constraint(
        "claim_planet_nonce_unique", "claim", ["planet_id", "nonce"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("claim_planet_nonce_unique", "claim", type_="unique")
    op.create_unique_constraint("claim_nonce_key", "claim", ["nonce"])
    # ### end Alembic commands ###
