"""Add planet_id columns

Revision ID: b0b9cb232f67
Revises: e1d1d1c1f914
Create Date: 2023-11-08 17:10:17.388277

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b0b9cb232f67"
down_revision: Union[str, None] = "e1d1d1c1f914"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "claim", sa.Column("planet_id", sa.LargeBinary(length=12), nullable=True)
    )
    op.execute("UPDATE claim SET planet_id = '0x000000000000'::bytea")
    op.alter_column("claim", "planet_id", nullable=False)
    op.add_column(
        "user_season_pass",
        sa.Column("planet_id", sa.LargeBinary(length=12), nullable=True),
    )
    op.execute("UPDATE user_season_pass SET planet_id = '0x000000000000'::bytea")
    op.alter_column("user_season_pass", "planet_id", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_season_pass", "planet_id")
    op.drop_column("claim", "planet_id")
    # ### end Alembic commands ###
