"""Adjust block table

Revision ID: bca8f726a5ee
Revises: c8e1e7686fc5
Create Date: 2025-08-11 18:38:15.331419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bca8f726a5ee'
down_revision: Union[str, None] = 'c8e1e7686fc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('block', sa.Column('last_processed_index', sa.BigInteger(), nullable=True))
    op.drop_constraint('block_by_pass_planet_unique', 'block', type_='unique')
    op.drop_index('idx_block_planet_pass_type_index', table_name='block')
    op.create_unique_constraint('block_by_planet_pass_type_unique', 'block', ['planet_id', 'pass_type'])
    op.create_index('idx_block_planet_pass_type', 'block', ['planet_id', 'pass_type'], unique=False)
    op.drop_column('block', 'index')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('block', sa.Column('index', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_index('idx_block_planet_pass_type', table_name='block')
    op.drop_constraint('block_by_planet_pass_type_unique', 'block', type_='unique')
    op.create_index('idx_block_planet_pass_type_index', 'block', ['planet_id', 'pass_type', 'index'], unique=False)
    op.create_unique_constraint('block_by_pass_planet_unique', 'block', ['planet_id', 'pass_type', 'index'])
    op.drop_column('block', 'last_processed_index')
    # ### end Alembic commands ###
