"""Add premium_plus column

Revision ID: ef5d7e33cf37
Revises: 97762c954f58
Create Date: 2023-10-25 23:56:32.717046

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ef5d7e33cf37"
down_revision: Union[str, None] = "97762c954f58"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_season_pass", sa.Column("is_premium_plus", sa.Boolean(), nullable=True)
    )
    op.execute("UPDATE user_season_pass SET is_premium_plus = 'False'")
    op.alter_column("user_season_pass", "is_premium_plus", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_season_pass", "is_premium_plus")
    # ### end Alembic commands ###
