"""Add details to action_history

Revision ID: 00a050a705c2
Revises: b0b9cb232f67
Create Date: 2023-11-10 00:12:50.503150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00a050a705c2'
down_revision: Union[str, None] = 'b0b9cb232f67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('action_history', sa.Column('block_index', sa.Integer(), nullable=True))
    op.execute("UPDATE action_history SET block_index = 0")
    op.alter_column("action_history", "block_index", nullable=False)
    op.add_column('action_history', sa.Column('tx_id', sa.Text(), nullable=True))
    op.execute("UPDATE action_history SET tx_id = '0000000000000000000000000000000000000000000000000000000000000000'")
    op.alter_column("action_history", "tx_id", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('action_history', 'tx_id')
    op.drop_column('action_history', 'block_index')
    # ### end Alembic commands ###
