"""Control season with datetime

Revision ID: 508b09040fa7
Revises: 77e337ab3c79
Create Date: 2023-12-14 11:25:57.324876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '508b09040fa7'
down_revision: Union[str, None] = '77e337ab3c79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('season_pass', 'start_date',
                    new_column_name="start_timestamp",
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('season_pass', 'end_date',
                    new_column_name='end_timestamp',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('season_pass', 'end_timestamp',
                    new_column_name="end_date",
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column('season_pass', 'start_timestamp',
                    new_column_name="start_date",
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    # ### end Alembic commands ###
