"""Add instant_reward column to season

Revision ID: 993ab160a6fc
Revises: 92c0120a4566
Create Date: 2023-11-17 18:59:08.612579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '993ab160a6fc'
down_revision: Union[str, None] = '92c0120a4566'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('season_pass', sa.Column('instant_exp', sa.Integer(), nullable=True))
    op.execute("UPDATE season_pass SET instant_exp=13350")  # season 1
    op.alter_column("season_pass", "instant_exp", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('season_pass', 'instant_exp')
    # ### end Alembic commands ###
