"""Add rewarded level columns

Revision ID: a3c500f38dc2
Revises: ef5d7e33cf37
Create Date: 2023-10-27 17:14:50.148600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a3c500f38dc2'
down_revision: Union[str, None] = 'ef5d7e33cf37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim', sa.Column('normal_levels', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.add_column('claim', sa.Column('premium_levels', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.execute("UPDATE claim SET normal_levels='{}'")
    op.execute("UPDATE claim SET premium_levels='{}'")
    op.alter_column("claim", "normal_levels", nullable=False)
    op.alter_column("claim", "premium_levels", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('claim', 'premium_levels')
    op.drop_column('claim', 'normal_levels')
    # ### end Alembic commands ###
