"""Add season_index column and index

Revision ID: ac1e86a25be3
Revises: 8b92be10e129
Create Date: 2024-10-28 17:59:51.047357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac1e86a25be3'
down_revision: Union[str, None] = '8b92be10e129'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('season_pass', sa.Column('season_index', sa.Integer(), nullable=True))
    op.execute('UPDATE season_pass SET season_index=id')
    op.alter_column("season_pass", "season_index", nullable=False)
    op.create_index('ix_pass_type_index_unique', 'season_pass', ['pass_type', 'season_index'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pass_type_index_unique', table_name='season_pass')
    op.drop_column('season_pass', 'season_index')
    # ### end Alembic commands ###
