"""Add battle history

Revision ID: c8e1e7686fc5
Revises: d7d731964ef7
Create Date: 2025-02-12 00:57:13.170667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8e1e7686fc5'
down_revision: Union[str, None] = 'd7d731964ef7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('battle_history',
    sa.Column('planet_id', sa.LargeBinary(length=12), nullable=False),
    sa.Column('battle_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('planet_id', 'battle_id', name='pk_battle_history')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('battle_history')
    # ### end Alembic commands ###
