"""Chane action_type column type

Revision ID: e1d1d1c1f914
Revises: 9a4dafd6163e
Create Date: 2023-11-07 14:00:28.457348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e1d1d1c1f914'
down_revision: Union[str, None] = '9a4dafd6163e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

ACTION_TYPE_ENUM = postgresql.ENUM(
    *("HAS", "SWEEP", "ARENA", "RAID"), name="actiontype", create_type=False
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE action_history ALTER action TYPE actiontype USING action::actiontype")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('action_history', 'action',
               existing_type=postgresql.ENUM('HAS', 'SWEEP', 'ARENA', 'RAID', name='actiontype'),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
