"""Add action handle history tables

Revision ID: f1944309b46c
Revises: a3c500f38dc2
Create Date: 2023-10-31 17:20:49.147126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1944309b46c'
down_revision: Union[str, None] = 'a3c500f38dc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('block',
    sa.Column('index', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('index')
    )
    op.create_index(op.f('ix_block_index'), 'block', ['index'], unique=False)
    op.create_table('action_history',
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('agent_addr', sa.Text(), nullable=False),
    sa.Column('avatar_addr', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('exp', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['season_pass.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_season_avatar', 'action_history', ['season_id', 'avatar_addr'], unique=False)
    op.create_index(op.f('ix_action_history_action'), 'action_history', ['action'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_action_history_action'), table_name='action_history')
    op.drop_index('idx_season_avatar', table_name='action_history')
    op.drop_table('action_history')
    op.drop_index(op.f('ix_block_index'), table_name='block')
    op.drop_table('block')
    # ### end Alembic commands ###
