name: Deploy NineChronicles.SeasonPass

#  https://github.com/actions/runner/issues/1490
on:
  workflow_dispatch:
    inputs:
      branch:
        required: true
        description: Target branch name to deploy
        type: string
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      ACCOUNT_ID:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      KMS_KEY_ID:
        required: true
      JWT_TOKEN_SECRET:
        required: true
      SLACK_WEBHOOK_URL:
        required: true
      HEADLESS_GQL_JWT_SECRET:
        required: true

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    outputs:
      url: ${{ steps.deployment.outputs.SERVICE_HOST }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch || github.ref }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Setup Node.JS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.6.1
          virtualenvs-in-project: true

      - name: Cache Poetry
        id: cache-poetry
        uses: actions/cache@v3
        with:
          path: .venv
          key: poetry-${{ runner.os }}-${{ hashFiles('poetry.lock') }}

      - name: Install dependencies
        run: |
          poetry install
          yarn add aws-cdk

      - name: Build API Layer
        run: |
          pushd season_pass
          poetry export --with=api --without-hashes -o requirements.txt
          pip install -r requirements.txt -t layer/python/lib/python3.11/site-packages/
          popd

      - name: Build Worker Layer
        run: |
          pushd worker
          poetry export --with=worker --without-hashes -o requirements.txt
          pip install -r requirements.txt -t layer/python/lib/python3.11/site-packages/
          popd

      - name: Synth stack
        env:
          STAGE: ${{ vars.STAGE }}
          REGION_NAME: ${{ vars.REGION_NAME }}
          ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          KMS_KEY_ID: ${{ secrets.KMS_KEY_ID }}
          JWT_TOKEN_SECRET: ${{ secrets.JWT_TOKEN_SECRET }}
          ODIN_VALIDATOR_URL: ${{ vars.ODIN_VALIDATOR_URL }}
          HEIMDALL_VALIDATOR_URL: ${{ vars.HEIMDALL_VALIDATOR_URL }}
          ODIN_GQL_URL: ${{ vars.ODIN_GQL_URL }}
          ODIN_SCAN_URL: ${{ vars.ODIN_SCAN_URL }}
          HEIMDALL_GQL_URL: ${{ vars.HEIMDALL_GQL_URL }}
          HEIMDALL_SCAN_URL: ${{ vars.HEIMDALL_SCAN_URL }}
          ODIN_INTERNAL_GQL_URL: ${{ vars.ODIN_INTERNAL_GQL_URL }}
          HEIMDALL_INTERNAL_GQL_URL: ${{ vars.HEIMDALL_INTERNAL_GQL_URL }}
          HEADLESS_GQL_JWT_SECRET: ${{ secrets.HEADLESS_GQL_JWT_SECRET }}
        run: |
          source $VENV
          yarn cdk synth

      - name: Deploy stack
        id: deployment
        env:
          STAGE: ${{ vars.STAGE }}
          REGION_NAME: ${{ vars.REGION_NAME }}
          ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          KMS_KEY_ID: ${{ secrets.KMS_KEY_ID }}
          JWT_TOKEN_SECRET: ${{ secrets.JWT_TOKEN_SECRET }}
          ODIN_VALIDATOR_URL: ${{ vars.ODIN_VALIDATOR_URL }}
          HEIMDALL_VALIDATOR_URL: ${{ vars.HEIMDALL_VALIDATOR_URL }}
          ODIN_GQL_URL: ${{ vars.ODIN_GQL_URL }}
          ODIN_SCAN_URL: ${{ vars.ODIN_SCAN_URL }}
          HEIMDALL_GQL_URL: ${{ vars.HEIMDALL_GQL_URL }}
          HEIMDALL_SCAN_URL: ${{ vars.HEIMDALL_SCAN_URL }}
          ODIN_INTERNAL_GQL_URL: ${{ vars.ODIN_INTERNAL_GQL_URL }}
          HEIMDALL_INTERNAL_GQL_URL: ${{ vars.HEIMDALL_INTERNAL_GQL_URL }}
          HEADLESS_GQL_JWT_SECRET: ${{ secrets.HEADLESS_GQL_JWT_SECRET }}
        run: |
          source $VENV
          yarn cdk deploy --all --require-approval never -O output.txt
          cat output.txt
          ARRAY=(`grep -e "https://.*/$STAGE/" output.txt | tr "\"", "\n"`)
          echo "SERVICE_HOST=${ARRAY[-1]}"
          echo "SERVICE_HOST=${ARRAY[-1]}" >> "$GITHUB_OUTPUT"

      - name: Upload host to ParameterStore
        id: upload_host
        env:
          STAGE: ${{ vars.STAGE }}
          REGION_NAME: ${{ vars.REGION_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          source $VENV
          python ./.github/scripts/upload_host.py ${{ steps.deployment.outputs.SERVICE_HOST }}

  slack_notification_on_success:
    uses: ./.github/workflows/slack_message.yml
    needs: deployment
    if: ${{ success() }}
    with:
      type: success
      environment: ${{ inputs.environment }}
      url: ${{ needs.deployment.outputs.url }}
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  slack_notification_on_failure:
    uses: ./.github/workflows/slack_message.yml
    needs: deployment
    if: ${{ failure() }}
    with:
      type: failure
      environment: ${{ inputs.environment }}
      url: ${{ needs.deployment.outputs.url }}
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

#      - name: Upgrade DB Schema
#        env:
#          STAGE: ${{vars.STAGE}}
#          REGION_NAME: ${{ vars.REGION_NAME }}
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#        run: |
#          source $VENV
#          pushd common
#          python scripts/update_alembic_ini.py
#          alembic upgrade head -n ${{vars.STAGE}}
#          popd
