name: Works on NineChronicles.SeasonPass

on:
  push:
    branches:
      - development
      - internal
      - release/*
      - main
      - preview
  pull_request:
    branches:
      - development
      - internal
      - release/*
      - main

jobs:
  test:
    uses: ./.github/workflows/test.yml
    with:
      environment: ${{ github.ref == 'refs/heads/main' && 'mainnet' || ((startsWith(github.ref, 'refs/heads/release') || github.ref == 'refs/heads/preview') && 'internal' || 'development') }}
    secrets:
      HEADLESS_GQL_JWT_SECRET: ${{ secrets.HEADLESS_GQL_JWT_SECRET }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
