name: Works on NineChronicles.SeasonPass

on:
  push:
    branches:
      - development
      - internal
      - release/*
      - main
      - preview
  pull_request:
    branches:
      - development
      - internal
      - release/*
      - main

jobs:
  test:
    uses: ./.github/workflows/test.yml
    with:
      environment: ${{ github.ref == 'refs/heads/main' && 'mainnet' || ((startsWith(github.ref, 'refs/heads/release') || github.ref == 'refs/heads/preview') && 'internal' || 'development') }}
    secrets:
      HEADLESS_GQL_JWT_SECRET: ${{ secrets.HEADLESS_GQL_JWT_SECRET }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  synth:
    uses: ./.github/workflows/synth.yml
    with:
      environment: ${{ github.ref == 'refs/heads/main' && 'mainnet' || ((startsWith(github.ref, 'refs/heads/release') || github.ref == 'refs/heads/preview') && 'internal' || 'development') }}
    secrets:
      ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      KMS_KEY_ID: ${{ secrets.KMS_KEY_ID }}
      JWT_TOKEN_SECRET: ${{ secrets.JWT_TOKEN_SECRET }}
      HEADLESS_GQL_JWT_SECRET: ${{ secrets.HEADLESS_GQL_JWT_SECRET }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  deploy_without_approval:
    # This is for development / internal deployment
    if: ${{ github.ref == 'refs/heads/internal' || github.ref == 'refs/heads/preview' || github.ref == 'refs/heads/development' || startsWith(github.ref, 'refs/heads/release') }}
    needs: [ "test", "synth" ]
    uses: ./.github/workflows/deploy.yml
    with:
      environment: ${{ (startsWith(github.ref, 'refs/heads/release') || github.ref == 'refs/heads/internal' || github.ref == 'refs/heads/preview') && 'internal' || 'development' }}
    secrets:
      ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      KMS_KEY_ID: ${{ secrets.KMS_KEY_ID }}
      JWT_TOKEN_SECRET: ${{ secrets.JWT_TOKEN_SECRET }}
      HEADLESS_GQL_JWT_SECRET: ${{ secrets.HEADLESS_GQL_JWT_SECRET }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  approval_notice:
    uses: ./.github/workflows/slack_message.yml
    needs: [ "test", "synth" ]
    if: ${{ github.ref == 'refs/heads/main' }}
    with:
      type: approval
      environment: ${{ (startsWith(github.ref, 'refs/heads/release') || github.ref == 'refs/heads/internal' || github.ref == 'refs/heads/preview') && 'internal' || 'development' }}
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  approval:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: [ "test", "synth" ]
    environment: approval
    steps:
      - uses: actions/checkout@v3

      - name: Echo
        run: |
          echo "Manual Approval"

  deploy_with_approval:
    # This is for mainnet deployment. It needs user approval
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: approval
    uses: ./.github/workflows/deploy.yml
    with:
      environment: mainnet
    secrets:
      ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      KMS_KEY_ID: ${{ secrets.KMS_KEY_ID }}
      JWT_TOKEN_SECRET: ${{ secrets.JWT_TOKEN_SECRET }}
      HEADLESS_GQL_JWT_SECRET: ${{ secrets.HEADLESS_GQL_JWT_SECRET }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
