on:
  workflow_call:
    inputs:
      type:
        required: true
        type: string
      environment:
        required: true
        type: string
      url:
        required: false
        type: string
    secrets:
      SLACK_WEBHOOK_URL:
        required: true

jobs:
  slack_message:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get Timestamp
        id: get_timestamp
        run: echo "TIME=$(date +"%Y-%m-%d %H:%M:%S %Z")" >> $GITHUB_OUTPUT

      - name: Slack message for success
        if: ${{ inputs.type == 'success' }}
        uses: slackapi/slack-github-action@v1.24.0
        env:
          STAGE: ${{ vars.STAGE }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "[NineChronicles.SeasonPass] Deployment Success :smile:",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Stage:*\n${{ vars.STAGE }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Branch:*\n${{ github.ref_name }}"
                    }
                  ]
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Deployment Timestamp:*\n${{ steps.get_timestamp.outputs.TIME }}"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": " "
                  },
                  "accessory": {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "Go and check",
                      "emoji": true
                    },
                    "style": "primary",
                    "url": "${{ inputs.url }}",
                    "action_id": "see-api-doc"
                  }
                }
              ]
            }



      - name: Slack message for failure
        if: ${{ inputs.type == 'failure' }}
        uses: slackapi/slack-github-action@v1.24.0
        env:
          STAGE: ${{ vars.STAGE }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "[NineChronicles.SeasonPass] Deployment Fail :sob:",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Stage:*\n${{ vars.STAGE }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Branch:*\n${{ github.ref_name }}"
                    }
                  ]
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Deployment Timestamp:*\n${{ steps.get_timestamp.outputs.TIME }}"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": " "
                  },
                  "accessory": {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "Checkout github actions",
                      "emoji": true
                    },
                    "style": "danger",
                    "url": "https://github.com/planetarium/NineChronicles.SeasonPass/actions/runs/${{ github.run_id }}",
                    "action_id": "see-github-actions"
                  }
                }
              ]
            }
